apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: diago
  labels:
    app.kubernetes.io/name: diago
    app.kubernetes.io/part-of: diago
    app.kubernetes.io/component: leader
spec:
  replicas: 1
  serviceName: diago
  selector:
    matchLabels:
      app.kubernetes.io/name: diago
  template:
    metadata:
      labels:
        app.kubernetes.io/name: diago
        app.kubernetes.io/part-of: diago
        app.kubernetes.io/component: leader
    spec:
      containers:
      - name: leader
        image: diago
        imagePullPolicy: Never
        env:
        - name: "DIAGO_HOST"
          valueFrom:
              fieldRef:
                fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: diago-cm
      terminationGracePeriodSeconds: 0
