apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diago-chaos-role
  labels:
    app.kubernetes.io/name: diago
    app.kubernetes.io/part-of: diago
    app.kubernetes.io/component: leader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
