apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: diago-role-binding
subjects:
- kind: ServiceAccount
  name: diago-sa
  namespace: diago
roleRef:
  kind: Role
  name: diago-role
  apiGroup: rbac.authorization.k8s.io