apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: diago-role
  labels:
    app.kubernetes.io/name: diago
    app.kubernetes.io/part-of: diago
    app.kubernetes.io/component: leader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["diago.app"]
  resources: ["workergroups"]
  verbs: ["get", "watch", "list", "create", "delete"]
