apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diago-chaos-role-binding
subjects:
- kind: ServiceAccount
  name: diago-sa
  namespace: diago
roleRef:
  kind: ClusterRole
  name: diago-chaos-role
  apiGroup: rbac.authorization.k8s.io