// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idl/proto/worker.proto

package worker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Payload:
	//	*Message_Register
	//	*Message_Start
	//	*Message_Finish
	//	*Message_Stop
	//	*Message_Ack
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type Message_Start struct {
	Start *Start `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type Message_Finish struct {
	Finish *Finish `protobuf:"bytes,3,opt,name=finish,proto3,oneof"`
}

type Message_Stop struct {
	Stop *Stop `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

func (*Message_Register) isMessage_Payload() {}

func (*Message_Start) isMessage_Payload() {}

func (*Message_Finish) isMessage_Payload() {}

func (*Message_Stop) isMessage_Payload() {}

func (*Message_Ack) isMessage_Payload() {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetRegister() *Register {
	if x, ok := m.GetPayload().(*Message_Register); ok {
		return x.Register
	}
	return nil
}

func (m *Message) GetStart() *Start {
	if x, ok := m.GetPayload().(*Message_Start); ok {
		return x.Start
	}
	return nil
}

func (m *Message) GetFinish() *Finish {
	if x, ok := m.GetPayload().(*Message_Finish); ok {
		return x.Finish
	}
	return nil
}

func (m *Message) GetStop() *Stop {
	if x, ok := m.GetPayload().(*Message_Stop); ok {
		return x.Stop
	}
	return nil
}

func (m *Message) GetAck() *Ack {
	if x, ok := m.GetPayload().(*Message_Ack); ok {
		return x.Ack
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Register)(nil),
		(*Message_Start)(nil),
		(*Message_Finish)(nil),
		(*Message_Stop)(nil),
		(*Message_Ack)(nil),
	}
}

type Register struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Instance             string   `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Frequency            uint64   `protobuf:"varint,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{1}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

func (m *Register) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Register) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *Register) GetFrequency() uint64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type HTTPRequest struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPRequest) Reset()         { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()    {}
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{2}
}

func (m *HTTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPRequest.Unmarshal(m, b)
}
func (m *HTTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPRequest.Marshal(b, m, deterministic)
}
func (m *HTTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPRequest.Merge(m, src)
}
func (m *HTTPRequest) XXX_Size() int {
	return xxx_messageInfo_HTTPRequest.Size(m)
}
func (m *HTTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPRequest proto.InternalMessageInfo

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Start struct {
	// Each job is split into multiple workloads, each workload with the same job id
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// requests / second
	Frequency uint64 `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// seconds
	Duration uint64       `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Request  *HTTPRequest `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	// Rate at which to persist response data.
	PersistResponseSamplingRate *SamplingRate `protobuf:"bytes,5,opt,name=persist_response_sampling_rate,json=persistResponseSamplingRate,proto3" json:"persist_response_sampling_rate,omitempty"`
	// Information about the test which contains the job.
	TestId               string   `protobuf:"bytes,10,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	TestInstanceId       string   `protobuf:"bytes,11,opt,name=test_instance_id,json=testInstanceId,proto3" json:"test_instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Start) Reset()         { *m = Start{} }
func (m *Start) String() string { return proto.CompactTextString(m) }
func (*Start) ProtoMessage()    {}
func (*Start) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{3}
}

func (m *Start) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Start.Unmarshal(m, b)
}
func (m *Start) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Start.Marshal(b, m, deterministic)
}
func (m *Start) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Start.Merge(m, src)
}
func (m *Start) XXX_Size() int {
	return xxx_messageInfo_Start.Size(m)
}
func (m *Start) XXX_DiscardUnknown() {
	xxx_messageInfo_Start.DiscardUnknown(m)
}

var xxx_messageInfo_Start proto.InternalMessageInfo

func (m *Start) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Start) GetFrequency() uint64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *Start) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Start) GetRequest() *HTTPRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Start) GetPersistResponseSamplingRate() *SamplingRate {
	if m != nil {
		return m.PersistResponseSamplingRate
	}
	return nil
}

func (m *Start) GetTestId() string {
	if m != nil {
		return m.TestId
	}
	return ""
}

func (m *Start) GetTestInstanceId() string {
	if m != nil {
		return m.TestInstanceId
	}
	return ""
}

type Finish struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Finish) Reset()         { *m = Finish{} }
func (m *Finish) String() string { return proto.CompactTextString(m) }
func (*Finish) ProtoMessage()    {}
func (*Finish) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{4}
}

func (m *Finish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Finish.Unmarshal(m, b)
}
func (m *Finish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Finish.Marshal(b, m, deterministic)
}
func (m *Finish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Finish.Merge(m, src)
}
func (m *Finish) XXX_Size() int {
	return xxx_messageInfo_Finish.Size(m)
}
func (m *Finish) XXX_DiscardUnknown() {
	xxx_messageInfo_Finish.DiscardUnknown(m)
}

var xxx_messageInfo_Finish proto.InternalMessageInfo

func (m *Finish) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type Stop struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop) Reset()         { *m = Stop{} }
func (m *Stop) String() string { return proto.CompactTextString(m) }
func (*Stop) ProtoMessage()    {}
func (*Stop) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{5}
}

func (m *Stop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop.Unmarshal(m, b)
}
func (m *Stop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop.Marshal(b, m, deterministic)
}
func (m *Stop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop.Merge(m, src)
}
func (m *Stop) XXX_Size() int {
	return xxx_messageInfo_Stop.Size(m)
}
func (m *Stop) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop.DiscardUnknown(m)
}

var xxx_messageInfo_Stop proto.InternalMessageInfo

func (m *Stop) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type Ack struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{6}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

type SamplingRate struct {
	// 1 in "period" sampling. <=0 values indicate no sampling.
	Period               int32    `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SamplingRate) Reset()         { *m = SamplingRate{} }
func (m *SamplingRate) String() string { return proto.CompactTextString(m) }
func (*SamplingRate) ProtoMessage()    {}
func (*SamplingRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d11beac452b9addf, []int{7}
}

func (m *SamplingRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SamplingRate.Unmarshal(m, b)
}
func (m *SamplingRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SamplingRate.Marshal(b, m, deterministic)
}
func (m *SamplingRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SamplingRate.Merge(m, src)
}
func (m *SamplingRate) XXX_Size() int {
	return xxx_messageInfo_SamplingRate.Size(m)
}
func (m *SamplingRate) XXX_DiscardUnknown() {
	xxx_messageInfo_SamplingRate.DiscardUnknown(m)
}

var xxx_messageInfo_SamplingRate proto.InternalMessageInfo

func (m *SamplingRate) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Register)(nil), "Register")
	proto.RegisterType((*HTTPRequest)(nil), "HTTPRequest")
	proto.RegisterType((*Start)(nil), "Start")
	proto.RegisterType((*Finish)(nil), "Finish")
	proto.RegisterType((*Stop)(nil), "Stop")
	proto.RegisterType((*Ack)(nil), "Ack")
	proto.RegisterType((*SamplingRate)(nil), "SamplingRate")
}

func init() { proto.RegisterFile("idl/proto/worker.proto", fileDescriptor_d11beac452b9addf) }

var fileDescriptor_d11beac452b9addf = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x6a, 0xdb, 0x3e,
	0x14, 0x76, 0x12, 0xdb, 0x89, 0x4f, 0xfa, 0xfb, 0x11, 0xc4, 0x96, 0x99, 0x74, 0x6b, 0x37, 0x5f,
	0x64, 0xb9, 0x99, 0x53, 0xba, 0x27, 0x68, 0x07, 0xc3, 0x61, 0x0c, 0x86, 0x52, 0x18, 0xf4, 0x26,
	0xc8, 0xb6, 0xe2, 0xaa, 0x71, 0x2c, 0x4d, 0x92, 0x19, 0x7d, 0x92, 0x3d, 0xca, 0x5e, 0x6f, 0x48,
	0x56, 0xb2, 0x76, 0xd0, 0x3b, 0x7d, 0x7f, 0x7c, 0xf8, 0xf4, 0x59, 0x07, 0xa6, 0xac, 0xac, 0x97,
	0x42, 0x72, 0xcd, 0x97, 0x3f, 0xb9, 0xdc, 0x51, 0x99, 0x5a, 0x30, 0x3b, 0xaf, 0x38, 0xaf, 0x6a,
	0xda, 0x49, 0x79, 0xbb, 0x5d, 0x6a, 0xb6, 0xa7, 0x4a, 0x93, 0xbd, 0xe8, 0x0c, 0xc9, 0xef, 0x1e,
	0x0c, 0xbf, 0x52, 0xa5, 0x48, 0x45, 0xd1, 0x7b, 0x18, 0x49, 0x5a, 0x31, 0xa5, 0xa9, 0x8c, 0x7b,
	0x6f, 0x7b, 0x8b, 0xf1, 0x65, 0x94, 0x62, 0x47, 0x64, 0x1e, 0x3e, 0x8a, 0xe8, 0x0c, 0x02, 0xa5,
	0x89, 0xd4, 0x71, 0xdf, 0xba, 0xc2, 0x74, 0x6d, 0x50, 0xe6, 0xe1, 0x8e, 0x46, 0xef, 0x20, 0xdc,
	0xb2, 0x86, 0xa9, 0xbb, 0x78, 0x60, 0x0d, 0xc3, 0xf4, 0xb3, 0x85, 0x99, 0x87, 0x9d, 0x80, 0x4e,
	0xc1, 0x57, 0x9a, 0x8b, 0xd8, 0xb7, 0x86, 0x20, 0x5d, 0x6b, 0x2e, 0x32, 0x0f, 0x5b, 0x12, 0xc5,
	0x30, 0x20, 0xc5, 0x2e, 0x0e, 0xac, 0xe6, 0xa7, 0x57, 0xc5, 0x2e, 0xf3, 0xb0, 0xa1, 0xae, 0x23,
	0x18, 0x0a, 0xf2, 0x50, 0x73, 0x52, 0x26, 0xb7, 0x30, 0x3a, 0x84, 0x43, 0x2f, 0x20, 0xa8, 0x24,
	0x6f, 0x85, 0x8d, 0x1d, 0xe1, 0x0e, 0xa0, 0x19, 0x8c, 0x58, 0xa3, 0x34, 0x69, 0x0a, 0x6a, 0x93,
	0x46, 0xf8, 0x88, 0xd1, 0x6b, 0x88, 0xb6, 0x92, 0xfe, 0x68, 0x69, 0x53, 0x3c, 0xd8, 0x94, 0x3e,
	0xfe, 0x4b, 0x24, 0x5f, 0x60, 0x9c, 0xdd, 0xdc, 0x7c, 0xc3, 0x06, 0x2b, 0x8d, 0xa6, 0x10, 0xee,
	0xa9, 0xbe, 0xe3, 0xa5, 0x9b, 0xef, 0x10, 0x9a, 0xc0, 0xa0, 0x95, 0xb5, 0x9b, 0x6d, 0x8e, 0x08,
	0x81, 0x9f, 0xf3, 0xb2, 0x9b, 0x18, 0x61, 0x7b, 0x4e, 0x7e, 0xf5, 0x21, 0xb0, 0x05, 0xa1, 0x97,
	0x10, 0xde, 0xf3, 0x7c, 0xc3, 0x0e, 0x73, 0x82, 0x7b, 0x9e, 0xaf, 0xca, 0xa7, 0x59, 0xfa, 0xff,
	0x64, 0x31, 0xb7, 0x28, 0x5b, 0x49, 0x34, 0xe3, 0x8d, 0x0b, 0x7a, 0xc4, 0x68, 0x0e, 0x43, 0xd9,
	0x65, 0x74, 0x45, 0x9e, 0xa4, 0x8f, 0x72, 0xe3, 0x83, 0x88, 0x30, 0x9c, 0x09, 0x2a, 0x15, 0x53,
	0x7a, 0x23, 0xa9, 0x12, 0xbc, 0x51, 0x74, 0xa3, 0xc8, 0x5e, 0xd4, 0xac, 0xa9, 0x36, 0x92, 0x68,
	0xea, 0xba, 0xfe, 0x2f, 0x5d, 0x3b, 0x16, 0x13, 0x4d, 0xf1, 0xa9, 0xfb, 0x08, 0xbb, 0x6f, 0x1e,
	0x8b, 0xe8, 0x15, 0x0c, 0x35, 0x55, 0xda, 0xdc, 0x06, 0xba, 0x56, 0x0c, 0x5c, 0x95, 0x68, 0x01,
	0x93, 0x4e, 0x70, 0x5d, 0x1b, 0xc7, 0xd8, 0x3a, 0xfe, 0xb7, 0x0e, 0x47, 0xaf, 0xca, 0xe4, 0x1c,
	0xc2, 0xee, 0x61, 0x3c, 0xd3, 0x4c, 0xf2, 0x06, 0x7c, 0xf3, 0x30, 0x9e, 0x93, 0x03, 0x18, 0x5c,
	0x15, 0xbb, 0x64, 0x0e, 0x27, 0x4f, 0x92, 0x4d, 0x21, 0x14, 0x54, 0x32, 0xf7, 0xbb, 0x02, 0xec,
	0xd0, 0xe5, 0x05, 0x84, 0xdf, 0xed, 0x72, 0xa0, 0x39, 0xc0, 0x27, 0xce, 0x65, 0xc9, 0x1a, 0xe3,
	0x1f, 0xa5, 0x6e, 0x03, 0x66, 0xc7, 0x53, 0xe2, 0x2d, 0x7a, 0x17, 0xbd, 0x6b, 0x74, 0x3b, 0xb1,
	0x6b, 0xf2, 0xa1, 0xa2, 0x8d, 0x5b, 0xac, 0x3c, 0xb4, 0xcc, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0x11, 0xe6, 0xbe, 0x73, 0x03, 0x00, 0x00,
}
