{
 "title": "Diago Dashboard",
 "templating": {
  "list": [
   {
    "name": "jobid",
    "label": "JobId",
    "query": "label_values(diago_requests,jobid)"
   },
   {
    "name": "instid",
    "label": "TestInstanceId",
    "query": "label_values(diago_requests,instanceid)"
   },
   {
    "name": "testid",
    "label": "TestId",
    "query": "label_values(diago_requests,testid)"
   }
  ]
 },
 "panels": [
  {
   "title": "Byte Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(diago_bytes_in{testid=~\"$testid\",instanceid=~\"$instid\",jobid=~\"$jobid\"})",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum(diago_bytes_out{testid=~\"$testid\",instanceid=~\"$instid\",jobid=~\"$jobid\"})",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(diago_latency_mean{testid=~\"$testid\",instanceid=~\"$instid\",jobid=~\"$jobid\"})",
     "legendFormat": "Latency Mean"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(diago_requests{testid=~\"$testid\",instanceid=~\"$instid\",jobid=~\"$jobid\"}[10s]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum(rate(diago_success{testid=~\"$testid\",instanceid=~\"$instid\",jobid=~\"$jobid\"}[10s]))",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "sum(rate(diago_requests{testid=~\"$testid\",instanceid=~\"$instid\",jobid=~\"$jobid\"}[10s]))-sum(rate(diago_success{testid=~\"$testid\",instanceid=~\"$instid\",jobid=~\"$jobid\"}[10s]))",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}