apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workergroups.diago.app
  labels:
    app.kubernetes.io/name: diago
    app.kubernetes.io/part-of: diago
spec:
  group: diago.app
  names:
    kind: WorkerGroup
    plural: workergroups
    singular: workergroup
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                type: string
            type: object
          spec:
            properties:
              image:
                type: string
              capacity:
                type: integer
              allowedInactivityPeriod:
                type: integer
              template:
                type: object
            type: object
            required:
            - image
            - capacity
        required:
        - apiVersion
        - kind
        - metadata
        - spec
