// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idl/proto/aggregator.proto

package aggregator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Payload:
	//	*Message_AggMetrics
	//	*Message_Metrics
	//	*Message_Finish
	//	*Message_Ack
	//	*Message_Register
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ec081b4c4f6f61, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_AggMetrics struct {
	AggMetrics *AggMetrics `protobuf:"bytes,1,opt,name=agg_metrics,json=aggMetrics,proto3,oneof"`
}

type Message_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,2,opt,name=metrics,proto3,oneof"`
}

type Message_Finish struct {
	Finish *Finish `protobuf:"bytes,3,opt,name=finish,proto3,oneof"`
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type Message_Register struct {
	Register *Register `protobuf:"bytes,5,opt,name=register,proto3,oneof"`
}

func (*Message_AggMetrics) isMessage_Payload() {}

func (*Message_Metrics) isMessage_Payload() {}

func (*Message_Finish) isMessage_Payload() {}

func (*Message_Ack) isMessage_Payload() {}

func (*Message_Register) isMessage_Payload() {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetAggMetrics() *AggMetrics {
	if x, ok := m.GetPayload().(*Message_AggMetrics); ok {
		return x.AggMetrics
	}
	return nil
}

func (m *Message) GetMetrics() *Metrics {
	if x, ok := m.GetPayload().(*Message_Metrics); ok {
		return x.Metrics
	}
	return nil
}

func (m *Message) GetFinish() *Finish {
	if x, ok := m.GetPayload().(*Message_Finish); ok {
		return x.Finish
	}
	return nil
}

func (m *Message) GetAck() *Ack {
	if x, ok := m.GetPayload().(*Message_Ack); ok {
		return x.Ack
	}
	return nil
}

func (m *Message) GetRegister() *Register {
	if x, ok := m.GetPayload().(*Message_Register); ok {
		return x.Register
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_AggMetrics)(nil),
		(*Message_Metrics)(nil),
		(*Message_Finish)(nil),
		(*Message_Ack)(nil),
		(*Message_Register)(nil),
	}
}

type Register struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ec081b4c4f6f61, []int{1}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

type Finish struct {
	TestId               string   `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	InstanceId           string   `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Finish) Reset()         { *m = Finish{} }
func (m *Finish) String() string { return proto.CompactTextString(m) }
func (*Finish) ProtoMessage()    {}
func (*Finish) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ec081b4c4f6f61, []int{2}
}

func (m *Finish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Finish.Unmarshal(m, b)
}
func (m *Finish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Finish.Marshal(b, m, deterministic)
}
func (m *Finish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Finish.Merge(m, src)
}
func (m *Finish) XXX_Size() int {
	return xxx_messageInfo_Finish.Size(m)
}
func (m *Finish) XXX_DiscardUnknown() {
	xxx_messageInfo_Finish.DiscardUnknown(m)
}

var xxx_messageInfo_Finish proto.InternalMessageInfo

func (m *Finish) GetTestId() string {
	if m != nil {
		return m.TestId
	}
	return ""
}

func (m *Finish) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *Finish) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type Metrics struct {
	TestId     string `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	JobId      string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Code       uint32 `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	BytesIn    uint64 `protobuf:"varint,5,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut   uint64 `protobuf:"varint,6,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	// Nanoseconds
	Latency int64  `protobuf:"varint,7,opt,name=latency,proto3" json:"latency,omitempty"`
	Error   string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// https://godoc.org/github.com/golang/protobuf/ptypes#TimestampProto
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ec081b4c4f6f61, []int{3}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetTestId() string {
	if m != nil {
		return m.TestId
	}
	return ""
}

func (m *Metrics) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *Metrics) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Metrics) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Metrics) GetBytesIn() uint64 {
	if m != nil {
		return m.BytesIn
	}
	return 0
}

func (m *Metrics) GetBytesOut() uint64 {
	if m != nil {
		return m.BytesOut
	}
	return 0
}

func (m *Metrics) GetLatency() int64 {
	if m != nil {
		return m.Latency
	}
	return 0
}

func (m *Metrics) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Metrics) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type AggMetrics struct {
	TestId     string            `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	InstanceId string            `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	JobId      string            `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Requests   uint64            `protobuf:"varint,4,opt,name=requests,proto3" json:"requests,omitempty"`
	Codes      map[string]uint64 `protobuf:"bytes,5,rep,name=codes,proto3" json:"codes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	BytesIn    uint64            `protobuf:"varint,6,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut   uint64            `protobuf:"varint,7,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	// Nanoseconds
	Latencies []*duration.Duration `protobuf:"bytes,8,rep,name=latencies,proto3" json:"latencies,omitempty"`
	// https://godoc.org/github.com/golang/protobuf/ptypes#TimestampProto
	Earliest             *timestamp.Timestamp `protobuf:"bytes,9,opt,name=earliest,proto3" json:"earliest,omitempty"`
	Latest               *timestamp.Timestamp `protobuf:"bytes,10,opt,name=latest,proto3" json:"latest,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,11,opt,name=end,proto3" json:"end,omitempty"`
	Errors               []string             `protobuf:"bytes,12,rep,name=errors,proto3" json:"errors,omitempty"`
	Finish               bool                 `protobuf:"varint,13,opt,name=finish,proto3" json:"finish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AggMetrics) Reset()         { *m = AggMetrics{} }
func (m *AggMetrics) String() string { return proto.CompactTextString(m) }
func (*AggMetrics) ProtoMessage()    {}
func (*AggMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ec081b4c4f6f61, []int{4}
}

func (m *AggMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggMetrics.Unmarshal(m, b)
}
func (m *AggMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggMetrics.Marshal(b, m, deterministic)
}
func (m *AggMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggMetrics.Merge(m, src)
}
func (m *AggMetrics) XXX_Size() int {
	return xxx_messageInfo_AggMetrics.Size(m)
}
func (m *AggMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_AggMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_AggMetrics proto.InternalMessageInfo

func (m *AggMetrics) GetTestId() string {
	if m != nil {
		return m.TestId
	}
	return ""
}

func (m *AggMetrics) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *AggMetrics) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *AggMetrics) GetRequests() uint64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *AggMetrics) GetCodes() map[string]uint64 {
	if m != nil {
		return m.Codes
	}
	return nil
}

func (m *AggMetrics) GetBytesIn() uint64 {
	if m != nil {
		return m.BytesIn
	}
	return 0
}

func (m *AggMetrics) GetBytesOut() uint64 {
	if m != nil {
		return m.BytesOut
	}
	return 0
}

func (m *AggMetrics) GetLatencies() []*duration.Duration {
	if m != nil {
		return m.Latencies
	}
	return nil
}

func (m *AggMetrics) GetEarliest() *timestamp.Timestamp {
	if m != nil {
		return m.Earliest
	}
	return nil
}

func (m *AggMetrics) GetLatest() *timestamp.Timestamp {
	if m != nil {
		return m.Latest
	}
	return nil
}

func (m *AggMetrics) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *AggMetrics) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *AggMetrics) GetFinish() bool {
	if m != nil {
		return m.Finish
	}
	return false
}

type Ack struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ec081b4c4f6f61, []int{5}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Register)(nil), "Register")
	proto.RegisterType((*Finish)(nil), "Finish")
	proto.RegisterType((*Metrics)(nil), "Metrics")
	proto.RegisterType((*AggMetrics)(nil), "AggMetrics")
	proto.RegisterMapType((map[string]uint64)(nil), "AggMetrics.CodesEntry")
	proto.RegisterType((*Ack)(nil), "Ack")
}

func init() { proto.RegisterFile("idl/proto/aggregator.proto", fileDescriptor_f2ec081b4c4f6f61) }

var fileDescriptor_f2ec081b4c4f6f61 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0xcd, 0x64, 0x26, 0xf3, 0xb8, 0xa1, 0x12, 0xb2, 0x4a, 0x71, 0x83, 0x44, 0xc3, 0x08, 0x41,
	0x16, 0x65, 0x8a, 0x02, 0x82, 0x8a, 0x5d, 0xcb, 0x43, 0xc9, 0xa2, 0x42, 0xb2, 0xd8, 0xc0, 0xa6,
	0x72, 0x66, 0x5c, 0xe3, 0x26, 0x1d, 0x17, 0xdb, 0x41, 0xca, 0x5f, 0xf0, 0x01, 0x7c, 0x14, 0x9f,
	0x84, 0x6c, 0xcf, 0x24, 0xa5, 0x48, 0x94, 0x45, 0x77, 0x3e, 0xf7, 0x1c, 0xdb, 0xf2, 0xb9, 0xc7,
	0x17, 0x06, 0xa2, 0x5a, 0x1c, 0x5c, 0x2a, 0x69, 0xe4, 0x01, 0xe5, 0x5c, 0x31, 0x4e, 0x8d, 0x54,
	0x85, 0x2b, 0x0c, 0xf6, 0xb8, 0x94, 0x7c, 0xc1, 0x3c, 0x3d, 0x5b, 0x9e, 0x1d, 0x18, 0x71, 0xc1,
	0xb4, 0xa1, 0x17, 0x97, 0x8d, 0xe0, 0xe1, 0x75, 0x41, 0xb5, 0x54, 0xd4, 0x08, 0x59, 0x7b, 0x3e,
	0xff, 0x15, 0x40, 0x72, 0xc2, 0xb4, 0xa6, 0x9c, 0xa1, 0x02, 0xfa, 0x94, 0xf3, 0xd3, 0x0b, 0x66,
	0x94, 0x28, 0x35, 0x0e, 0x86, 0xc1, 0xa8, 0x3f, 0xee, 0x17, 0x47, 0x9c, 0x9f, 0xf8, 0xd2, 0xa4,
	0x43, 0x80, 0xae, 0x11, 0x7a, 0x0c, 0x49, 0xab, 0xed, 0x3a, 0x6d, 0x5a, 0x6c, 0x84, 0x2d, 0x85,
	0x1e, 0x41, 0x7c, 0x26, 0x6a, 0xa1, 0xbf, 0xe2, 0xd0, 0x89, 0x92, 0xe2, 0x83, 0x83, 0x93, 0x0e,
	0x69, 0x08, 0x84, 0x21, 0xa4, 0xe5, 0x1c, 0x47, 0x8e, 0x8f, 0x8a, 0xa3, 0x72, 0x3e, 0xe9, 0x10,
	0x5b, 0x42, 0x4f, 0x21, 0x55, 0x8c, 0x0b, 0x6d, 0x98, 0xc2, 0x3d, 0x47, 0x67, 0x05, 0x69, 0x0a,
	0x93, 0x0e, 0x59, 0x93, 0xc7, 0x19, 0x24, 0x97, 0x74, 0xb5, 0x90, 0xb4, 0xca, 0x01, 0xd2, 0x56,
	0x92, 0x7f, 0x86, 0xd8, 0xdf, 0x86, 0xee, 0x43, 0x62, 0x98, 0x36, 0xa7, 0xa2, 0x72, 0x0f, 0xcb,
	0x48, 0x6c, 0xe1, 0xb4, 0x42, 0x7b, 0xd0, 0x17, 0xb5, 0x36, 0xb4, 0x2e, 0x99, 0x25, 0xbb, 0x8e,
	0x84, 0xb6, 0x34, 0xad, 0xd0, 0x3d, 0x88, 0xcf, 0xe5, 0xcc, 0x72, 0xa1, 0xe3, 0x7a, 0xe7, 0x72,
	0x36, 0xad, 0xf2, 0x1f, 0x5d, 0xeb, 0x9c, 0x7f, 0xe3, 0x6d, 0x1f, 0x8e, 0x10, 0x44, 0xa5, 0xac,
	0x98, 0xb3, 0x64, 0x8b, 0xb8, 0x35, 0xda, 0x85, 0x74, 0xb6, 0x32, 0x4c, 0x9f, 0x8a, 0xda, 0x79,
	0x11, 0x91, 0xc4, 0xe1, 0x69, 0x8d, 0x1e, 0x40, 0xe6, 0x29, 0xb9, 0x34, 0x38, 0x76, 0x9c, 0xd7,
	0x7e, 0x5c, 0x1a, 0x84, 0x21, 0x59, 0x50, 0xc3, 0xea, 0x72, 0x85, 0x93, 0x61, 0x30, 0x0a, 0x49,
	0x0b, 0xd1, 0x36, 0xf4, 0x98, 0x52, 0x52, 0xe1, 0xd4, 0xdf, 0xed, 0x00, 0x3a, 0x84, 0x6c, 0x9d,
	0x22, 0x9c, 0x39, 0xd3, 0x07, 0x85, 0x8f, 0x51, 0xd1, 0xc6, 0xa8, 0xf8, 0xd4, 0x2a, 0xc8, 0x46,
	0x9c, 0xff, 0x8c, 0x00, 0x36, 0x69, 0xb9, 0x7d, 0x57, 0x06, 0x36, 0x0d, 0xdf, 0x96, 0x4c, 0x1b,
	0xed, 0x9c, 0x89, 0xc8, 0x1a, 0xa3, 0x7d, 0xe8, 0x59, 0x97, 0x34, 0xee, 0x0d, 0xc3, 0x51, 0x7f,
	0xbc, 0x73, 0x25, 0xb6, 0xc5, 0x5b, 0x4b, 0xbc, 0xaf, 0x8d, 0x5a, 0x11, 0x2f, 0xfa, 0xc3, 0xcb,
	0xf8, 0x1f, 0x5e, 0x26, 0xd7, 0xbc, 0x7c, 0x0d, 0x99, 0x37, 0x4f, 0x30, 0x8d, 0x53, 0x77, 0xd3,
	0xee, 0x5f, 0xde, 0xbc, 0x6b, 0xbe, 0x18, 0xd9, 0x68, 0xd1, 0x2b, 0x48, 0x19, 0x55, 0x0b, 0xc1,
	0xb4, 0xf9, 0x0f, 0x4f, 0xd7, 0x5a, 0x34, 0x86, 0xd8, 0x1e, 0xa2, 0x0d, 0x86, 0x1b, 0x77, 0x35,
	0x4a, 0xb4, 0x0f, 0x21, 0xab, 0x2b, 0xdc, 0xbf, 0x71, 0x83, 0x95, 0xa1, 0x1d, 0x88, 0x5d, 0xdf,
	0x35, 0xbe, 0x33, 0x0c, 0x6d, 0x93, 0x3c, 0xb2, 0xf5, 0xe6, 0xdf, 0x6e, 0x0d, 0x83, 0x51, 0xda,
	0x7e, 0xd6, 0xc1, 0x21, 0xc0, 0xc6, 0x4f, 0x74, 0x17, 0xc2, 0x39, 0x5b, 0x35, 0xfd, 0xb5, 0x4b,
	0x1b, 0xaa, 0xef, 0x74, 0xb1, 0x64, 0xae, 0xad, 0x11, 0xf1, 0xe0, 0x4d, 0xf7, 0x30, 0xc8, 0x7b,
	0x10, 0x1e, 0x95, 0xf3, 0xf1, 0x4b, 0x17, 0x92, 0x66, 0x8e, 0xa1, 0x27, 0xf6, 0x38, 0xa9, 0x2a,
	0x51, 0x53, 0xc3, 0x90, 0x9d, 0x20, 0x6e, 0x18, 0x0d, 0xd6, 0xab, 0xbc, 0x33, 0x0a, 0x9e, 0x07,
	0xc7, 0x3b, 0x5f, 0xb6, 0xdd, 0x0b, 0x9e, 0x71, 0x56, 0x5f, 0x99, 0x83, 0xb3, 0xd8, 0x55, 0x5f,
	0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x30, 0x67, 0x58, 0x26, 0x05, 0x00, 0x00,
}
