apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: mongodb
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
