name: Test + Coverage Reports

push:
  branches:
    - main
    - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: |
        make test
        mv cover.out coverage.txt
        bash <(curl -s https://codecov.io/bash)
