name: Test

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: docker build .

    - name: Test
      run: |
        make test
        mv coverage.out coverage.txt
        bash <(curl -s https://codecov.io/bash)
